name: CI

on: [push]

env:
  CI: true
  YARN_CACHE_FOLDER: .cache/yarn

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version-file: .node-version
      - uses: actions/cache@v3
        with:
          path: ${YARN_CACHE_FOLDER}
          key: ${{ runner.os }}-yarn-cache-v1
      - run: yarn
      - run: yarn lint
      - run: yarn test:ci
      - run: yarn build
